### ISSUE TITLE
Add some spacing between sidebar and footer

### ISSUE THREAD

**Issue by kaiwood** [UPDIP/updip.github.io#19]
![screenshot](https://cloud.githubusercontent.com/assets/7542/16895591/378c915a-4b7c-11e6-8614-1a66cadf68af.jpg)

**Comment by blumenkraft** [comment]
Awesome! Thank's @tdrabold. 💯

**Comment by kaiwood** [comment]
98 points. 

![unknown 1](https://cloud.githubusercontent.com/assets/7542/16897146/ce59a736-4ba8-11e6-9f80-6e99bdc9713e.jpg)

**Comment by blumenkraft** [comment]
Papperlapapp!

**Comment by kaiwood** [comment]
🖖

**Comment by tdrabold** [comment]
![pic](https://cloud.githubusercontent.com/assets/897761/16897197/9021b326-4baa-11e6-9223-7214bb0fcc6f.png)

**Comment by blumenkraft** [comment]
⚡
