### ISSUE TITLE
Randomly arrange list

### ISSUE THREAD

**Issue by kaiwood** [UPDIP/updip.github.io#2]

**Comment by blumenkraft** [comment]
The balls of steel award goes to  @kaiwood ⭐

**Comment by blumenkraft** [comment]
Broke the Lorem Ipsum

**Comment by kaiwood** [comment]
Broke what?

**Comment by blumenkraft** [comment]
Sorry, browser glitch on my side. You did just fine.

**Comment by kaiwood** [comment]
Oh, but search seems to be broken... I'll take a look into.

**Comment by kaiwood** [comment]
Resolved via fb041b12ffb2fc02a656afc4ad8a5a1d5c1cdb4d

**Comment by kaiwood** [comment]
fb041b12ffb2fc02a656afc4ad8a5a1d5c1cdb4d breaks loading of images. Argh!

/edit Nah, looks like that was just my slow connection, never mind

**Comment by blumenkraft** [comment]
Great job! 👡

**Comment by blumenkraft** [comment]
Oh dear this thread is like a rollercoaster!

**Comment by kaiwood** [comment]
Yep, but now its closed, case closed.

**Comment by blumenkraft** [comment]
:)
