### ISSUE TITLE
Build auto updater for avatars

### ISSUE THREAD

**Issue by blumenkraft** [UPDIP/updip.github.io#20]

**Comment by kaiwood** [comment]
We did this!

**Comment by blumenkraft** [comment]
Something is weird with it though. There are not always all the avatars available.

**Comment by kaiwood** [comment]
Yep, noticed this too. I updated the whole script yesterday after hitting the rate limit again. Thought that fixed it, but you are right, I checked before bedtime and they where gone again.

I'll take a look at it, the download process should not delete the images we already got.

**Comment by kaiwood** [comment]
I think I found it. Should have removed the cron job with the old version of the script that still had the bad behaviour. New versions seems to be working fine.

BTW., I'm going to create another repo under this organisation with the fetch script, as its a separate piece of software. If it fails again, issues can go there.

**Comment by blumenkraft** [comment]
great idea!
