### ISSUE TITLE
Refactoring all the things

### ISSUE THREAD

**Issue by blumenkraft** [UPDIP/updip.github.io#31]

**Comment by kaiwood** [comment]
Not helpful as a task description, closing

**Comment by blumenkraft** [comment]
This one was demanded by you iirc...  ;)

**Comment by kaiwood** [comment]
Of course I demanded this. I demand things all the time :D

What I meant is that refactoring is an ongoing  and mandatory process, so it doesn't make sense to keep it open as an issue of its own.

**Comment by blumenkraft** [comment]
I see!
