### ISSUE TITLE
Add collapsed view for all cards 

### ISSUE THREAD

**Issue by kaiwood** [UPDIP/updip.github.io#4]

**Comment by kaiwood** [comment]
Wat?

**Comment by blumenkraft** [comment]
@kaiwood design anyone?

**Comment by kaiwood** [comment]
Wat?

**Comment by kaiwood** [comment]
Screenshot or it didn't happen.

**Comment by blumenkraft** [comment]
OPEN YOUR FUCKING BROWSER FOR GODS SAKE!

**Comment by kaiwood** [comment]
WIP, see origin/menu

**Comment by kaiwood** [comment]
Its collapsing. I don't like it, but it works.

**Comment by blumenkraft** [comment]
Don't like it either. Was a stupid idea of mine. We might undo this at some point?
